### ISSUE TITLE
In the UI there's no way to see what genome or gff has been selected

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/BamQC#1]
We should have some indication in the UI that a genome has been selected so it's clear what the user is using for their analysis.  Maybe a status bar at the bottom?  Even just updating the window label would help.

**Comment by pdp10** [comment]
Yes, I can do that. 
Once the analyses are terminated, the genome and the annotation file are already reported in the module Basic Statistics.

**Comment by pdp10** [comment]
By "window label" do you mean the window title? If so, I could add something like: 
BamQC ~ filename_with_path . 
which is set when something is loaded, and restored to BamQC, once the files are processed. 

Would this work be okay with you?

**Comment by s-andrews** [comment]
Yes to start with this would be fine.  It would either be the filename for the gff or the name of the network genome selected.

Simon.

**Comment by pdp10** [comment]
It should be okay now.

**Comment by pdp10** [comment]
This info is now reported in a status bar at the bottom of bamqc. The code for showing this in the title is now commented. Does this work on Mac OS X?

**Comment by ewels** [comment]
Yup:
![image](https://cloud.githubusercontent.com/assets/465550/11237871/884617c2-8de2-11e5-80b2-84633ebda104.png)

Would it be possible to have this on the central home screen as well? Took me a little while to find it. I would naïvely expect it to be above / below the _Use File > Open to select.._ text.

**Comment by pdp10** [comment]
The genome or the annotation file name are now reported on the central screen when these files are loaded.

**Comment by ewels** [comment]
Apologies, I wasn't very clear, I more meant here:

![image](https://cloud.githubusercontent.com/assets/465550/11240824/e379214e-8df5-11e5-9bed-cc0587c2a524.png)

But what you've done is also great :)
