### ISSUE TITLE
Download genome status

### ISSUE THREAD

**Issue by ewels** [s-andrews/BamQC#10]
Minor thing, but when downloading a new genome the status updates go into the terminal and not the GUI (which just waits). Might be nicer if they were printed in the graphical interface somewhere instead.

**Comment by ewels** [comment]
Similar thing for when the analysis is ongoing. Would be nice to have the latest status message shown in the GUI?

**Comment by pdp10** [comment]
The text is now printed in the graphical interface. If BamQC is executed on a commandline, the progress is printed on the shell. Thanks.

**Comment by pdp10** [comment]
Actually I apologise, the text I moved to the graphical interface is about the "annotation loading". I haven't yet done it for the "annotation downloading" part.

**Comment by ewels** [comment]
Nice! Super fast :)

**Comment by pdp10** [comment]
The download progress is now reported on right of the status panel.

**Comment by ewels** [comment]
Super nice :+1:
