### ISSUE TITLE
Genome Coverage plot - sort chromosomes

### ISSUE THREAD

**Issue by ewels** [s-andrews/BamQC#11]
When I plot the genome coverage plot, I get this:
![image](https://cloud.githubusercontent.com/assets/465550/11237987/285aaec6-8de3-11e5-8f55-4d7a671cba6c.png)

Two suggestions:
1. Trim `chromosome` and `chr` from names for plotting
   - Would save space and probably make sorting easier
2. Sort the chromosomes

**Comment by ewels** [comment]
Also, I'm a bit confused about what each line is showing - where the y axis limits are basically. Could it be a filled area curve instead of just a line?

**Comment by pdp10** [comment]
I included your two suggestions and it looks better now. Thanks. 
In the plot above, the red lines indicate z-scores of log10 (binCounts). 

In my last commit I removed the log10(binCounts), so the red lines are now z-scores of counts. Using the z-score alone, makes these lines too flat though. In the examples I have, you cannot see any spikes (corresponding to std devs). I am not sure that transforming the binCounts to log10 before computing the z-score is correct. Although log is monotone, I found that in some cases this does not work well.. 

![gc_with_log10](https://cloud.githubusercontent.com/assets/11337972/11247541/6354091a-8e14-11e5-9cbe-e965749a66b9.png)

Without log10, the plot above looks like: 

![gc_with_log11](https://cloud.githubusercontent.com/assets/11337972/11247602/aee34d28-8e14-11e5-9a61-0d25578126a7.png)

**Comment by ewels** [comment]
Ah ok, z-score is a nice approach. What's your test sample? It could be that the lines are meant to be flat? It would be nice to have a test sample with a known copy number variation.

Also, could it be worth making a special case for regions that have 0 coverage (like centromeres)? Perhaps just a blank line, or a grey shading or something..

**Comment by pdp10** [comment]
Thanks!
I found that example on the Internet but I know that those are points with 0 coverage, because I printed them. I think treating the regions having 0 coverage as a special case as you suggested makes sense. 

Using the log10 helps enlarge the differences where the coverage is >0. As it is now this is not well plot to me (second plot). This because the mean and sd used for computing the z-scores consider the points with 0 coverage. I was thinking to exclude these points from the computation of mean+sd so that the grey horizontal line passes through the spikes. The points with 0 coverage would either not be plotted or be plotted but with a different colour. 
Would this be correct in your opinion?

**Comment by ewels** [comment]
Yup, agreed that the mean will be more informative without the zero counts. I think that anything to exaggerate differences is probably good? These effects are likely to be fairly subtle (at most around 0.5X or 2X the normal counts). But I guess that the auto-scaling of the plot should adjust, so I'm not sure that I really have much opinion over whether to use log10 or not.

I think that it would probably look best if the zero count areas had their background shaded in a light grey. Very rough photoshop attached to explain what I mean:

![image](https://cloud.githubusercontent.com/assets/465550/11267686/104ea2cc-8ead-11e5-86d4-672a94f1d166.png)

This way, it's clear that there is no data for this region, but that there is reference sequence here.

**Comment by pdp10** [comment]
Okay, I'll see what I can do. Thanks!

**Comment by pdp10** [comment]
The regions with no coverage are now not represented with the red line but indicated with a black horizontal line at the bottom for now. 
I am not sure darker rectangles work fine for plots like the first one on this thread and I believe having the same notation is important to not confuse people. 

X axis labels are also simplified.
