### ISSUE TITLE
More y axis labels

### ISSUE THREAD

**Issue by ewels** [s-andrews/BamQC#13]
Loving some of these plots chaps, great work!

One thing I'm missing is some y-axis labels on some of the plots.. I can guess some (eg. insert size distribution - percentage of library?), but it would be nicer to have labels explicitly saying what the numbers are.

**Comment by pdp10** [comment]
Thanks for your suggestion. I added the labels for the y axes. The text might not final, but the functionality is there. If we decide to remove the label and represent the plot as before, this is straightforward.
When you have some time, could you let me know if you have better suggestion for the y-label text, please?
Cheers, Piero

**Comment by ewels** [comment]
Great, thanks! I'll take a look next time I run it..
