### ISSUE TITLE
Chromosome read density plot needs labels

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/BamQC#17]
The new chromosome read density plot needs to have labels on the points, otherwise you can't tell which is which.  I realise they're going to be crowded for the majority, but it's the outliers which are going to be the most interesting anyway.

**Comment by s-andrews** [comment]
The fix implemented seems to just have names in the interactive program - it doesn't do anything if you're looking at the HTML report (which is what most people will do).  They really need to be added to the plot as fixed items.  I realise this will mean the plots are more messy, but we do need to have them.

**Comment by pdp10** [comment]
Okay, I see what I can do. I will remove the tooltip and add a label.

**Comment by pdp10** [comment]
I merged this hotfix in the devel and master branches (pull request #20). I will try to find out a way to show all the labels so that they don't overlap.
