### ISSUE TITLE
README needs a build section

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/BamQC#2]
The instructions on the readme currently say do clone the repo from git and then follow the install instructions, but that doesn't provide a compiled version of the program, just source code.  Can we add a build document to say how to build from source.  Eventually we'll have a binary distribution as well, but it would be good to have source build instructions.

**Comment by ewels** [comment]
+1 for this one :wink:

**Comment by pdp10** [comment]
I just added a section containing the instructions for compiling BamQC in the README.
