### ISSUE TITLE
SNP Frequencies are not reported

### ISSUE THREAD

**Issue by vamst** [s-andrews/BamQC#24]
Hello,

I was trying to assess the bam quality on some external data and was particularly interested in the SNP frequencies over the reads.

For some reason the SNP parts were not reported at all and the "Percent SNPs" is 0.000 in the summary.
The indels are there though. There were no error messages during the processing.
The version I used was '0.1.0_devel'. The reference genome was hg19, bam header was present.

Are the SNP calculations somehow depending on the bam file (missing some tags, etc) and is there any way to force it?

Thanks,
Vyacheslav

![aaa](https://user-images.githubusercontent.com/17004138/30538922-5c9a465e-9c70-11e7-8d8a-4acc0072b26b.png)

**Comment by pdp10** [comment]
Hi Vyacheslav, 

If "Percent SNPs" is 0 in the summary, then no plot for the SNP is generated, because there is nothing to plot in this case. 
This is likely to be because your bam file is in one of the following cases:  
- doesn't contain any SNPs
- doesn't contain any MD string
- doesn't contain any Cigar string
- does contain inconsistencies between MD and Cigar strings  

Could you post the table of basic statistics, please? 

Regards,
Piero

**Comment by vamst** [comment]
Hi Piero,

Thanks for your answer.  The table with basic statistics is below.

As I see now there is a problem with MD tags, which are not present in 99.856% of reads. Unfortunately I don't have any details on how the alignment was done and why is the MD tag is missed for most of the reads. There are plenty of SNPs when looking in IGV.

Is the any way to use only CIGAR for SNPs assessment or the MDs are absolutely necessary?

Thanks,
Vyacheslav

Measure | Value
-- | --
File name | 11787_WGC074707D_control.rmdup.bam
Command generating Sam/Bam file | ID:MarkDuplicates  VN:2.6.0-<...>
Has annotation | No
Total chromosomes | 25
Sufficient genome coverage | Yes
Total sequences | 457414945
Percent primary alignments | 99.367
Percent sequences failed vendor QC | 0.000
Percent marked duplicate | 0.000
Percent sequences spliced | 0.000
Percent sequences paired | 100.000
Percent sequences properly paired | 97.641
Percent singletons | 0.125
Percent sequences unmapped | 0.144
Percent sequences without MD Tag String | 99.856
Percent sequences without Cigar String | 0.000
Percent sequences with inconsistent Cigar or MD Tag Strings | 0.000
Percent sequences discarded for variant call detection | 0.144
Percent indels | 0.072 (Ins: 0.034; Del: 0.037)
Percent SNPs | 0.000
Percent soft clips | 1.499

**Comment by vamst** [comment]
I guess, the MD tag is necessary to check SNPs by type (A->C, A->G, etc) since the bases itselt are not in the CIGAR. But the CIGAR alone should be enough to calculate general SNP frequencies, isn't it?

Nevertheless, there is a special samtools module "calcmd" which could add MD tag to a bam file having the reference fasta provided: https://www.biostars.org/p/42266/. I'm going to try that and then hopefully could get the BamQC SNPs reports. That's just a bit annoying, the bams are huge..,

Thanks,
Slava
