### ISSUE TITLE
Allow filter when listing genomes on the command line

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/BamQC#3]
When you run bamqc -b you currently get a list of everything available on the server, which is a very big list.

It would be better if b could be parameterised - so that if you supply some text afterwards it would only show lines which matched.

```
bamqc -b 
```

would still get you everything, but

```
bamqc -b mus
```

would only show you cases where the species or assembly contained 'mus' somewhere in them.

**Comment by pdp10** [comment]
Added. 

$ ./bamqc -b mus
List of genomes (species [ assemblies ]) retrieved from the Babraham Servers:
Mus musculus [ GRCm38 | NCBIM33 | NCBIM34 | NCBIM35 | NCBIM36 | NCBIM37 ]

$ ./bamqc -b m?s
List of genomes (species [ assemblies ]) retrieved from the Babraham Servers:
B anthracis Ames [ EB1 ]
B anthracis Ames ancestor [ EB1 ]
B licheniformis Goettingen [ EB1 ]
B licheniformis Novozymes [ EB1 ]
Monodelphis domestica [ MonDom5 | MonDom_4.0 ]
Mus musculus [ GRCm38 | NCBIM33 | NCBIM34 | NCBIM35 | NCBIM36 | NCBIM37 ]
